### ISSUE TITLE
host

### ISSUE THREAD

**Issue by majovec** [TransendStudios/TrinketPM#1]
[Tesseract] [22:55:11] CRITICAL> Trinket\Utils\Exceptions\SocketError: "Unknown Error Occured: Unable to connect to host server" (EXCEPTION) in "/plugins/TrinketPM-master/src/Trinket/Network/Client/TCPClientSocket" at line 39
 and in config is not host

**Comment by ImagicalGamer** [comment]
It's not completed yet, a github.com/TransendStudios/Trinket server will be required.
